### ISSUE TITLE
Two errors and one suggested parenthesis.

### ISSUE THREAD

**Issue by spairo1741** [cfrankb/esp-idf-cs3#2]
- this on new board Arduino esp32 Nano , ILi9341
![Capture-1](https://github.com/cfrankb/esp-idf-cs3/assets/29607074/7e90b8b0-1541-4dc3-9c23-6ecfdbe8fd7e)
![Capture-2](https://github.com/cfrankb/esp-idf-cs3/assets/29607074/787157a7-32db-4018-ab38-5c6a8e66372c)
![Capture-3](https://github.com/cfrankb/esp-idf-cs3/assets/29607074/8ae080dd-c0d0-45d1-8e6d-138522556aa1)

**Comment by cfrankb** [comment]
@spairo1741  please let me know if there are other issues.

**Comment by spairo1741** [comment]
- invalid arguments
- 
![Capture-4](https://github.com/cfrankb/esp-idf-cs3/assets/29607074/03a7b474-262b-4abb-9d2d-dea030c991aa)

**Comment by cfrankb** [comment]
This should fix this issue
https://github.com/cfrankb/esp-idf-cs3/commit/ed4c15527f2ec8ad7c50f130349e30f41c4631e0

@spairo1741  let me know if there is anything else

**Comment by spairo1741** [comment]
- no errors  after compilation.
