### ISSUE TITLE
No screen after change configuration.

### ISSUE THREAD

**Issue by spairo1741** [cfrankb/esp-idf-cs3#3]
- configures the project to meet your requirements.
after compilation, the screen only shows the starting board and then a screen probably with the words " level".
changes introduced in joystick.cpp
`#define JOYSTICK_SW GPIO_NUM_3
#define JOYSTICK_A_BUTTON GPIO_NUM_4

#define EXAMPLE_ADC1_CHAN0          ADC_CHANNEL_0       // pin 35 (x) BROWN
#define EXAMPLE_ADC1_CHAN1          ADC_CHANNEL_1       // pin 34 (y) WHITE`
SW --> GPIO3, buttonA --> GPIO4, used ADC1_CH0, ADC1_CH1

**Comment by cfrankb** [comment]
I am not sure what to do about this. 
you need a combination of settings that don't conflict.
since the buttons are not necessary, they can be disabled. i can prepare patch for that.

**Comment by spairo1741** [comment]
- in generic_gpio (gpio_example_main.c) for esp32s3 
- `#define GPIO_OUTPUT_IO_0    CONFIG_GPIO_OUTPUT_0
#define GPIO_OUTPUT_IO_1    CONFIG_GPIO_OUTPUT_1
#define GPIO_OUTPUT_PIN_SEL  ((1ULL<<GPIO_OUTPUT_IO_0) | (1ULL<<GPIO_OUTPUT_IO_1))
/*
 * Let's say, GPIO_OUTPUT_IO_0=18, GPIO_OUTPUT_IO_1=19
 * In binary representation,
 * 1ULL<<GPIO_OUTPUT_IO_0 is equal to 0000000000000000000001000000000000000000 and
 * 1ULL<<GPIO_OUTPUT_IO_1 is equal to 0000000000000000000010000000000000000000
 * GPIO_OUTPUT_PIN_SEL                0000000000000000000011000000000000000000
 * */
#define GPIO_INPUT_IO_0     CONFIG_GPIO_INPUT_0
#define GPIO_INPUT_IO_1     CONFIG_GPIO_INPUT_1
#define GPIO_INPUT_PIN_SEL  ((1ULL<<GPIO_INPUT_IO_0) | (1ULL<<GPIO_INPUT_IO_1))
/*
 * Let's say, GPIO_INPUT_IO_0=4, GPIO_INPUT_IO_1=5
 * In binary representation,
 * 1ULL<<GPIO_INPUT_IO_0 is equal to 0000000000000000000000000000000000010000 and
 * 1ULL<<GPIO_INPUT_IO_1 is equal to 0000000000000000000000000000000000100000
 * GPIO_INPUT_PIN_SEL                0000000000000000000000000000000000110000
 * */
`
