### ISSUE TITLE
Configure X and Y Axis

### ISSUE THREAD

**Issue by cfrankb** [cfrankb/esp-idf-cs3#5]
Add channels to the ConfigMenu for X and Y Axis.
Add Reverse Axis Option to ConfigMenu for X and Y Axis.

![Screenshot_2023-12-12_10-07-02](https://github.com/cfrankb/esp-idf-cs3/assets/3089730/345888fb-fa01-404f-90bf-969f71e37247)

**Comment by cfrankb** [comment]
![Screenshot_2023-12-12_10-13-04](https://github.com/cfrankb/esp-idf-cs3/assets/3089730/b3ad612a-c413-4dcd-8d9f-1e13a4ef5a7a)
![Screenshot_2023-12-12_10-12-50](https://github.com/cfrankb/esp-idf-cs3/assets/3089730/d8b54623-2fc3-47d1-816d-b86476337b97)

**Comment by cfrankb** [comment]
https://github.com/cfrankb/esp-idf-cs3/commit/d7690e8468e610c132f523648a31e0e7d9f40946

**Comment by cfrankb** [comment]
I have ordered one of these 
https://vi.aliexpress.com/item/1005004528153988.html

**Comment by spairo1741** [comment]
- working !
- 
![ADC_channel](https://github.com/cfrankb/esp-idf-cs3/assets/29607074/cf3f2bc1-addf-4165-b90e-2e5a4d7b4594)
